[package]
name = "valve-rcon"
license="MIT"
authors=["DigitalCyan"]
description="Implementation of Valve's RCON in Rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
